import Head from 'next/head'
import Link from 'next/link';
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Avanhala FnB Menu</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <div className={styles.thirteen}>
            <h2 className={inter.className}>Welcome to Avanhala Fnb</h2>
          </div>
        </div>
        <Link className={styles.viewMenu} href="/menu">View our Menu</Link>
      </main>
    </>
  )
}
