import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Menu() {
  return (
    <>
      <Head>
        <title>Avanhala FnB Menu</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <div className={styles.thirteen}>
            <h2 className={inter.className}>Food menu</h2>
          </div>
        </div>
        <p>Menu items will be listed soon...</p>
      </main>
    </>
  )
}
